apiVersion: v1
kind: Service
metadata:
  name: {{ include "chat-service.fullname" . }}-server
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "chat-service.labels" . | nindent 4 }}
    app: chat-server
spec:
  type: {{ .Values.chatServer.service.type }}
  selector:
    app: chat-server
  ports:
    - port: {{ .Values.chatServer.service.port }}
      targetPort: {{ .Values.chatServer.service.targetPort }}
      {{- if eq .Values.chatServer.service.type "NodePort" }}
      nodePort: {{ .Values.chatServer.service.nodePort }}
      {{- end }}

