{{- if .Values.chatServer.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "chat-service.fullname" . }}-hpa
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "chat-service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "chat-service.fullname" . }}-server
  minReplicas: {{ .Values.chatServer.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.chatServer.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.chatServer.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.chatServer.autoscaling.targetMemoryUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.chatServer.autoscaling.behavior.scaleDown.stabilizationWindowSeconds }}
      policies:
        {{- range .Values.chatServer.autoscaling.behavior.scaleDown.policies }}
        - type: {{ .type }}
          value: {{ .value }}
          periodSeconds: {{ .periodSeconds }}
        {{- end }}
      selectPolicy: {{ .Values.chatServer.autoscaling.behavior.scaleDown.selectPolicy }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.chatServer.autoscaling.behavior.scaleUp.stabilizationWindowSeconds }}
      policies:
        {{- range .Values.chatServer.autoscaling.behavior.scaleUp.policies }}
        - type: {{ .type }}
          value: {{ .value }}
          periodSeconds: {{ .periodSeconds }}
        {{- end }}
      selectPolicy: {{ .Values.chatServer.autoscaling.behavior.scaleUp.selectPolicy }}
{{- end }}

